### ISSUE TITLE
HEVC support?

### ISSUE THREAD

**Issue by laurfb** [winshining/nginx-http-flv-module#108]
Hi. Not a bug but a wish :)
Could you add HEVC/H.265 support for rtmp/HLS like aileone project https://github.com/aileone/nginx-rtmp-module ?
I think it would be useful although is beyond Adobe specs...
regards,
laur

**Comment by winshining** [comment]
As I've mentioned in #61 #105, I won't add the feature unless FLV spec is updated. In fact, the HEVC support for HLS in the project you posted is MEANINGLESS, because the latest HLS spec demands that if HEVC is used for video, the container format MUST NOT be ts but fMP4:

    1.5. The container format for HEVC video MUST be fMP4. 

You can see [HLS spec](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices) for details.
Thus, if I now add unofficial HEVC support for FLV (so publishers and players will also be unofficial) and someday Adobe updates the FLV spec and its content is hugely different from the current version, what I do will also be MEANINGLESS.
