### ISSUE TITLE
[bug] HTTPS support for on_publish

### ISSUE THREAD

**Issue by datagutt** [winshining/nginx-http-flv-module#130]
### Expected behavior
I can use https-urls in on_publish and on_publish_done
### Actual behavior
I get the following error complaining about invalid port.
``nginx: [emerg] invalid port in url "https://127.0.0.1/api/stream/on_publish" in /opt/nginx/conf/nginx.conf:45``

### Steps to reproduce the behavior 
1.
Use the following config in the rtmp application.
``
on_publish https://127.0.0.1/api/stream/on_publish;
on_publish_done https://127.0.0.1/api/stream/on_publish_done;
``

**Comment by TheRealMattLear** [comment]
Hi,

I can also confirm this is the case for push directive.

For example, the following:

```
push rtmps://live-api-s.facebook.com:443/rtmp/abcd;
```

Returns:
```
nginx: [emerg] invalid port in url "rtmps://live-api-s.facebook.com:443/rtmp/abcd" in /opt/nginx/conf/nginx.conf:10
```

**Comment by winshining** [comment]
Encrypted HTTP is not suppported in commands `on_xxx`.
@TheRealMattLear you can use stunnel to convert rtmp to rtmps.

**Comment by TheRealMattLear** [comment]
> @TheRealMattLear you can use stunnel to convert rtmp to rtmps.

For push targets i would imagine this to be requirement, especially since facebook ONLY accepts secure connections. Using a 3rd party tool to achieve a secure connection is a work around rather than a complete solution. Could I create a feature request for this instead?

**Comment by winshining** [comment]
@TheRealMattLear 
Well, secure RTMP feature will not be supported in this open source project.
In fact, I've developed this new feature since I saw Facebook announced that it would ONLY accept RTMPS on May 1st, 2019 and now it works well as a server or downstream server. I've spent so much time on it and it's cost me much on cloud server, domain name (some sites, Facebook for example, and encryption certificates doesn't support naked IP) and encryption certificates to test it. So, I will not open the source and it is non-free.
However, it can be provided for some one who has contributed important features to this open source project for free. 
For more details, you can contact me via E-Mail :)

**Comment by TheRealMattLear** [comment]
Hi,

For now we have managed to have this working by using ffmpeg to pass-thru the stream. This uses minimal resources on the system. Thank you



Best Regards

Matthew Lear – Director


________________________________
