### ISSUE TITLE
The clock rate during play video by HTTP-FLV is slower compared to the normal clock rate.

### ISSUE THREAD

**Issue by Sectran** [winshining/nginx-http-flv-module#259]
At the beginning, the time interval between the streaming machine's clock and the playback time for the HTTP-FLV  was around 10 seconds. After a while, this time interval increased. I'm not sure if it's due to a discrepancy in clock rates between the HTTP-FLV streaming  and the actual clock rates, or if there are other reasons.
nginx version:1.22
nginx-http-module version:lasted
OS:Linux
at the begainning:
left is rtmp and right is http-flv
<img width="922" alt="image" src="https://github.com/winshining/nginx-http-flv-module/assets/150984071/3611d16e-1999-414e-a4d9-2bfd62dbf725">

in a while:

<img width="844" alt="image" src="https://github.com/winshining/nginx-http-flv-module/assets/150984071/2baa004b-4300-412b-8f9e-33e6be26a919">

You can see he time interval has increased, and what I can confirm is that the clock rate during RTMP streaming is correct.

by the way,I play flv useing flv.min.js,this is a demo:
```js
    <div class="mainContainer">
        <video controls controlslist="nodownload noplaybackrat" id="my-video" autoplay
            class="LiveVideo video-js vjs-default-skin">Your browser is too
            old which doesn't support HTML5 video.</video>
        <br>
    </div>
    <script>
        var player = document.getElementById('my-video');
        var videoPath = 'http://host ipaddr:80/live?port=1935&app=myapp&stream=test'
        function flv_load(urlPath) {
            flvPlayer = flvjs.createPlayer({
                type: 'flv',
                isLive: true,
                url: urlPath
            });
            flvPlayer.attachMediaElement(player);
            flvPlayer.load();
        }
        window.onload = function () {
            flv_load(videoPath);
        }
    </script>
```

**Comment by winshining** [comment]
Make sure your network is well. Normally, the delay of HTTP-FLV is about 1~5s (without GOP cache). It seems that HTTP-FLV halted (maybe caused by server timeout). By the way, there is cumulative delay in HTTP-FLV streaming because of network jitter. In other words, TCP is a reliable delivery protocol, it may delay in network, player must wait for delayed packets, that is out of control of server. Further, HTTP-FLV is not as interactive as RTMP, so delay in HTTP-FLV streaming is often larger than RTMP. Players can discard too delayed packets to catch up the streaming pace.
