### ISSUE TITLE
Does this module support H.265?

### ISSUE THREAD

**Issue by HeyJupiter** [winshining/nginx-http-flv-module#61]
Hi, @winshining, you've done such a great job! I've searched a long time to see if there are some modules meet my needs that pull streams through http-flv.

But I found it didn't support H.265, right? Do you have a plan to add the feature?

**Comment by winshining** [comment]
No.
If Adobe doesn't update FLV tag to support H.265 officially, ffmpeg won't support it, you can see [ticket6389](http://trac.ffmpeg.org/ticket/6389). Moreover, players won't support H.265 over RTMP neither. Someone has attempted to add private tags for FLV. However, it will cost so much to adapt publishers, servers and players to support the private tags, because it is not GENERAL.

**Comment by matiaspl** [comment]
Maybe you could consider adding SRT support like Wowza had. This would open
the possibility of using H.265 (ffmpeg can be used as a live encoder as it
already supports SRT output).

20.08.2018 04:36 "winshining" <notifications@github.com> napisał(a):

No.
If Adobe doesn't update FLV tag to support H.265 officially, ffmpeg won't
support it, you can see ticket6389 <http://trac.ffmpeg.org/ticket/6389>.
Moreover, players won't support H.265 over RTMP neither. Someone has
attempted to add private tags for FLV. However, it will cost so much to
adapt publishers, servers and players to support the private tags, because
it is not GENERAL.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/winshining/nginx-http-flv-module/issues/61#issuecomment-414181374>,
or mute the thread

**Comment by winshining** [comment]
@matiaspl What does `SRT` mean?

**Comment by matiaspl** [comment]
SRT stands for Secure Reliable Transport - https://www.srtalliance.org/.
It's a quite advanced opensource protocol that allows sending data streams
(usually "broadcast tv" style MPEG-TS) to be sent over IP networks with
encryption, packet retransmission and forward error correction. There's a
public repository at https://github.com/Haivision/srt

pon., 20 sie 2018 o 10:11 winshining <notifications@github.com> napisał(a):

**Comment by HeyJupiter** [comment]
@winshining Thanks for your patient reply. So I have to re-encode my media file into H.264 :(
@matiaspl Are there any specifications about SRT then?
