### ISSUE TITLE
Could you please tell me who uses this module?

### ISSUE THREAD

**Issue by HeyJupiter** [winshining/nginx-http-flv-module#70]
Hi, @winshining, the module has been running perfectly for me for some time!
I saw the release note of version 1.2.4 wrote that some vendors had used this module in production, could you please tell me who are them? Cause I plan to use it in my product.
Thanks!

**Comment by winshining** [comment]
I've ever asked a sponsor that if I could list the company name in my README, he refused. They provide network TV service, using HTTP-FLV.
Another vendor has used the module to provide CDN service for some live show vendors, using RTMP. But there is a problem has not been solved until now, you can see #30. Dynamically reload configuration file without reloading Nginx is too complex for me.
A program manager in HUAWEI told me in Apr. that they planned to use the module and they were intensively testing the module. But they have not contacted me since then, so I can't make sure that if they at last decided to use it.
The most of other vendors use the module in their surveillance systems.
At last, you can search in GitHub to see if it is used by someone.
